### ISSUE TITLE
Aegisub 64位中加载失败

### ISSUE THREAD

**Issue by cqjjjzr** [qwe7989199/Lyric-Importer-for-Aegisub#2]
环境：Aegisub 3.2.2 64-bit
Windows 10 Build 1809(17763) x64

在按照指引装入文件后运行Aegisub提示如下错误。

![image](https://user-images.githubusercontent.com/6622592/56094287-6fff7a80-5f05-11e9-949e-a5aa07038582.png)

请问能否提供一个64位Aegisub可用的版本？
感谢。

**Comment by qwe7989199** [comment]
![image](https://user-images.githubusercontent.com/10990771/56101282-44a87a00-5f5d-11e9-9c41-60c5a38839d2.png)
![image](https://user-images.githubusercontent.com/10990771/56101289-5427c300-5f5d-11e9-8fe9-9f4275bfb56d.png)
64位能不能有，看的是tx老爷
顺便引用官网原话：不推荐使用64位版本，即使您使用的是64位Windows。64位版本可能存在32位版本没有的Bug。
There are not really any advantages to the 64-bit builds, and they exist only because they aren't much extra work and some people really wanted them for whatever reason.
顺便64bit luajit的ffi也没有全部测试通过

**Comment by wangqr** [comment]
> 64位能不能有，看的是tx老爷

https://github.com/wangqr/QQMusicDES/releases

**Comment by wangqr** [comment]
> 顺便64bit luajit的ffi也没有全部测试通过

luajit是一个无人维护项目。在目前的测试中，luajit会在使用Address Sanitizer时报内存越界访问，所以我合理怀疑其存在恶性bug。Aegisub可能在将来舍弃luajit，并迁回至lua5.3或5.4，过渡期使用[facebookarchive/luaffifb](https://github.com/facebookarchive/luaffifb)（亦已停止维护）。原版lua不含ffi模块，是否可能考虑采用其它方法加载c代码？

PS: 可能有用的链接：http://www.lua.org/pil/26.2.html

**Comment by qwe7989199** [comment]
> luajit是一个无人维护项目。在目前的测试中，luajit会在使用Address Sanitizer时报内存越界访问，所以我合理怀疑其存在恶性bug。Aegisub可能在将来舍弃luajit，并迁回至lua5.3或5.4，过渡期使用[facebookarchive/luaffifb](https://github.com/facebookarchive/luaffifb)（亦已停止维护）。原版lua不含ffi模块，是否可能考虑采用其它方法加载c代码？
> 
> PS: 可能有用的链接：http://www.lua.org/pil/26.2.html

就这个歌词插件来说：
因为当时是基于Aegisub最后一个稳定版3.2.2做的，ffi是最佳方案
剩下的那个动态链接库是这个https://github.com/SuJiKiNen/LyricDecoder (by @SuJiKiNen )
感谢QQLyric的解码库，64位Aegisub有空会测试
关于以后的版本：
原版Lua的C API看起来麻烦不少，不过应该可以实现（关键在于我不会写C）

其他方面：
我在字幕方面的工作主要在特效上（好像除此之外做字幕的过程中也没有什么高强度调用Lua运算的必要），在这方面很多老旧的特效函数库比如Yutils等都严重依赖于ffi这个接口，这也是我还在用32位版本的原因。不如说现在整个字幕流程其实都是为了功能和效率做出了稳定性和兼容性的牺牲，已经习惯了。迁移回原版lua的确解决了一些影响使用的bug，不过在字幕特效上的迁移成本略高，当然对一般用户来说肯定是稳定性第一，还是支持一个。

**Comment by qwe7989199** [comment]
Now it supports Aegisub 64bit version.
